server:
    port: 8889

spring:
    profiles:
        active: production
    application:
        name: config-client
    cloud:
        config:
            discovery:
                enabled: true
                service-id: CONFIG-SERVER
            allow-override:
                fail-fast: true
            retry:
                max-attempts: 50
                initial-interval: 1500
                multiplier: 1.5
    config:
        import: configserver:http://CONFIG-SERVER
        # import: 'configserver:http://localhost:8888'

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:7002/eureka/
    instance:
        prefer-ip-address: true
        instance-id: config-client
        hostname: localhost

management:
    endpoint:
        shutdown:
            enabled: false
    endpoints:
        web:
            exposure:
                include: "*"