spring:
    cloud:
        stream:
            ddddefault:
                producer:
                    useNativeEncoding: true
            bindings:
                producer-out-0:
                    contentType: application/*+avro
                    destination: test.avro.topic
                    producer:
                        useNativeEncoding: true
            kafka:
                binder:
                    auto-create-topics: true
                    brokers: localhost:9092
                bindings:
                    producer-out-0:
                        producer:
                            useNativeEncoding: true
                            configuration:
                                key:
                                    serializer: org.apache.kafka.common.serialization.LongSerializer
                                value:
                                    serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                                schema:
                                    registry:
                                        url: http://localhost:8081
#    main:
#        allow-bean-definition-overriding: true