server.port: 5001
spring:
    application:
        name: cloud-gateway
    cloud:
      gateway:
          discovery:
            locator:
                enabled: true
          routes:
              - id: provider
                uri: lb://SERVICE-PROVIDER
                predicates:
                  - Path=/provider/**
                  - Method=GET
                filters:
                  - RewritePath=/provider, /
eureka:
    instance:
        instance-id: testing-gateway-5001
        hostname: localhost
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/