server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: test-consumer

spring:
  application:
    name: testing-consumer
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# see HystrixFeignTestClient
feign:
  circuitbreaker:
    enabled: true

# allow to access hystrix dashboard
hystrix:
  dashboard:
    proxy-stream-allow-list: 'localhost'
  shareSecurityContext: true

provider:
  url: http://service-provider

logging.level:
  com.example: DEBUG
feign.client.config:
  default.loggerLevel: full
