spring:
    cloud:
        stream:
            function:
                definition: consumer;generatedConsumer
            bindings:
                consumer-in-0:
                    contentType: application/*+avro
                    destination: test.avro.topic
                generatedConsumer-in-0:
                    contentType: application/*+avro
                    destination: test.avro.generated.topic
            kafka:
                binder:
                    auto-create-topics: true
                    brokers: localhost:9092
                bindings:
                    consumer-in-0:
                        consumer:
                            useNativeEncoding: true
                            configuration:
                                key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
                                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                                schema.registry.url: http://localhost:8081
                    generatedConsumer-in-0:
                        consumer:
                            configuration:
                                key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
                                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                                schema.registry.url: http://localhost:8081
                                specific.avro.reader: true

application:
    elastic:
        enable: true